// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace classlibrary
{
    public partial class Java
    {
        public int? Courseid { get; set; }
        public string Levels { get; set; }
        public int Qid { get; set; }
        public string Question { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Correctans { get; set; }
    }

}