// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace classlibrary
{
    public partial class Loginuser
    {
        public int Userid { get; set; }
        public string Username { get; set; }
        public string Userpwd { get; set; }

        public virtual Register UsernameNavigation { get; set; }
    }
}