// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace classlibrary
{
    public partial class Loginadmin
    {
        public int Adminid { get; set; }
        public string Adminname { get; set; }
        public string Adminpwd { get; set; }
    }
}