// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace classlibrary
{
    public partial class Register
    {
        
        public Register()
        {
            Loginusers = new HashSet<Loginuser>();
        }

        public int Registerid { get; set; }

        [Key]
        [Column("username")]
        [StringLength(20)]
        
        public string Username { get; set; }
        [Key]
        [Column("firstname")]
        [StringLength(20)]
        public string Firstname { get; set; }
        [Key]
        [Column("lastname")]
        [StringLength(20)]
        public string Lastname { get; set; }
        [Column("pwd")]
        [StringLength(20)]
       
        public string Pwd { get; set; }
        [Column("confirmpwd")]
        [StringLength(20)]
        public string Confirmpwd { get; set; }
        [Column("dob", TypeName = "date")]
        public DateTime? Dob { get; set; }
        [Column("email")]
        [StringLength(20)]
        public string Email { get; set; }
        [Column("gender")]
        public bool? Gender { get; set; }
        [Column("phone")]
        [StringLength(20)]
        public string Phone { get; set; }
        [Column("nationality")]
        [StringLength(20)]
        public string Nationality { get; set; }

        public virtual ICollection<Loginuser> Loginusers { get; set; }
    }
}