// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace classlibrary
{
    public partial class Report
    {
        public string Username { get; set; }
        public int? Userid { get; set; }
        public int? Sourceid { get; set; }
        public string Coursename { get; set; }
        public string Levels { get; set; }
        public int? Totalmarks { get; set; }
        public string Statuss { get; set; }
    }
}