// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace classlibrary
{
    public partial class Techincal
    {
        public int? Courseid { get; set; }
        public string Levels { get; set; }
        public string Coursename { get; set; }
    }
}